client = lazop.LazopClient(url, appkey ,appSecret)
request = lazop.LazopRequest('/review/seller/list','GET')
request.add_api_param('item_id', '111111111')
request.add_api_param('order_id', '2222222')
request.add_api_param('start_time', '1621872000000')
request.add_api_param('end_time', '1622044800000')
request.add_api_param('content_filter', 'WITH_CONTENT,WITH_IMAGE_OR_VIDEO')
request.add_api_param('status_filter', 'NOT_REPLIED')
request.add_api_param('page_size', '10')
request.add_api_param('current', '1')
response = client.execute(request, access_token)
print(response.type)
print(response.body)